import google.generativeai as genai

class QuestionGenerator:
    def __init__(self, api_key) -> None:
        genai.configure(api_key = api_key)
        self.model = genai.GenerativeModel("gemini-pro")

    def generate_question(self, skill_tested: str, examples: list) -> str:
        """
        Generate question based on the skill to be tested and examples provided

        Parameters:
        -----------
        examples: List of samples questions if any
        skill_tested: List of skills that needs to be tested

        Returns:
        -----------
        Questions that is generated by the question generator
        """

        # print("Generating question to test ", skill_tested)
        prompt = f"""You are a question generator responsible for generating only one question based on the sample questions provided below. Remember that you have to generate question to test {skill_tested} skillset.
        question and answer.
        
        Examples:
        """
        for question in examples:
            tmp = f"""
            Question: {question}
            """
            prompt += tmp

        # print("Final prompt: ", prompt)

        response = self.model.generate_content(prompt)
        # response = self.model.generate_content_async(prompt)

        return response.text
